### ISSUE TITLE
404 on `/c/{categoryslug}/l/hot` route

### ISSUE THREAD

**Issue by oskarrough** [danskdynamit/discourse-hot-topics#2]
Hi, found a minor issue. If you browse to a category and then tap the "hot/popular" in the navigation you end up on an error page. The URL for a category on our end looks like this:

http://example.com/c/category-name/l/hot

**Comment by joebuhlig** [comment]
Should be resolved with this: https://github.com/danskdynamit/discourse-hot-topics/commit/36a8b2241f010941a996aeca6c6f0e0aac374559
