### ISSUE TITLE
Broken with the last Discourse update ?

### ISSUE THREAD

**Issue by ghost** [danskdynamit/discourse-hot-topics#4]
It seems that the plugin suffers from the update to Ember 2.4 by Discourse. When I try to go on the Hot pages, it doesn't work, I have a blank page or an error page asking me to try again.

I don't know if it helps but here are the error logs : 

`edited`

**Comment by oskarrough** [comment]
Thank you for reporting.

@joebuhlig any idea?

**Comment by ghost** [comment]
Little update. I though the error was related to this plugin but it seems it was Topic Preview who broke it. This hot topics plugin works fine.

sorry about that
